### ISSUE TITLE
Fix old comments that have gone missing

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/jeffgeerling-com#66]
I just noticed some old comments seem to have died off...

For example, on http://localhost/blog/2009/engaging-story, I found:

<img width="543" alt="Screen Shot 2020-04-28 at 2 41 06 PM" src="https://user-images.githubusercontent.com/481677/80530220-4e313400-895e-11ea-89e9-c9ae058166cd.png">

Nodes to test:

  - http://localhost/blog/2009/engaging-story
  - http://localhost/comment/1 (to test with the first ever comment on the Drupal site—over 10 years ago!)

**Comment by geerlingguy** [comment]
It looks like there are two alternating error messages, first:

```
Warning: strpos() expects parameter 1 to be string, object given in Drupal\Component\Utility\UrlHelper::stripDangerousProtocols() (line 359 of /var/www/html/web/core/lib/Drupal/Component/Utility/UrlHelper.php)
#0 /var/www/html/web/core/includes/bootstrap.inc(600): _drupal_error_handler_real(2, 'strpos() expect...', '/var/www/html/w...', 359, Array)
#1 [internal function]: _drupal_error_handler(2, 'strpos() expect...', '/var/www/html/w...', 359, Array)
#2 /var/www/html/web/core/lib/Drupal/Component/Utility/UrlHelper.php(359): strpos(Object(Drupal\Core\Url), ':')
#3 /var/www/html/web/core/lib/Drupal/Component/Render/FormattableMarkup.php(211): Drupal\Component\Utility\UrlHelper::stripDangerousProtocols(Object(Drupal\Core\Url))
#4 /var/www/html/web/core/lib/Drupal/Core/StringTranslation/TranslatableMarkup.php(195): Drupal\Component\Render\FormattableMarkup::placeholderFormat('@author \xE2\x80\x93 <a ...', Array)
#5 /var/www/html/web/core/lib/Drupal/Component/Utility/ToStringTrait.php(15): Drupal\Core\StringTranslation\TranslatableMarkup->render()
#6 /var/www/html/web/sites/default/files/php/twig/5ea882e7be937_comment.html.twig_5YGT0bAF_4T1MIEmNtgM1ZX7W/HCL1g3xbzqQ2qIAb-_hHUUdDJjVVpim7tYB-qi-j4h8.php(80): Drupal\Core\StringTranslation\TranslatableMarkup->__toString()
#7 /var/www/html/vendor/twig/twig/src/Template.php(455): __TwigTemplate_64abb5c464dda24161914a28f6a08ce58d0b342f5347d0c55c689eb8323d5acc->doDisplay(Array, Array)
#8 /var/www/html/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /var/www/html/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array)
#10 /var/www/html/web/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array)
#11 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('themes/jeffgeer...', Array)
#12 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\Core\Theme\ThemeManager->render('comment', Array)
#13 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(444): Drupal\Core\Render\Renderer->doRender(Array)
#14 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender(Array, false)
#15 /var/www/html/web/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\Core\Render\Renderer->render(Array)
#16 /var/www/html/web/sites/default/files/php/twig/5ea882e7be937_field--comment.html.twig_D1VBgT12HIypygtkerrgvZlUU/QGle11mOh6SyBYSTM8DSIj5u16z_CFOXY3sXEhMlgy4.php(89): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#17 /var/www/html/vendor/twig/twig/src/Template.php(455): __TwigTemplate_b93024b24b018a6bc0e5f3cd6487b188671f4b5d0d9fd1b7e7e64dbabf16a9f6->doDisplay(Array, Array)
#18 /var/www/html/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /var/www/html/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array)
#20 /var/www/html/web/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array)
#21 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('core/themes/cla...', Array)
#22 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\Core\Theme\ThemeManager->render('field', Array)
#23 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(444): Drupal\Core\Render\Renderer->doRender(Array)
#24 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender(Array, false)
#25 /var/www/html/web/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\Core\Render\Renderer->render(Array)
#26 /var/www/html/web/sites/default/files/php/twig/5ea882e7be937_node.html.twig_Q_r-oj8RBX8urhYfoi6O1Oug1/71k0mtTWxtuHd3uEAHv0y2jWov8Wh67J02rholIC6pM.php(129): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#27 /var/www/html/vendor/twig/twig/src/Template.php(455): __TwigTemplate_877dbf8a58c10b74d1cd7df929c8e8709709393ac254d58f85b24aed610dd9ea->doDisplay(Array, Array)
#28 /var/www/html/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /var/www/html/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array)
#30 /var/www/html/web/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array)
#31 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('themes/jeffgeer...', Array)
#32 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\Core\Theme\ThemeManager->render('node', Array)
#33 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender(Array, false)
#34 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(226): Drupal\Core\Render\Renderer->render(Array, false)
#35 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#36 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(227): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#37 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(117): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#38 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#39 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#40 /var/www/html/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#41 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(156): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent))
#42 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#43 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#44 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#45 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#46 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#47 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#48 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#49 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#50 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(694): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#51 /var/www/html/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#52 {main}
```

Second:

```
Warning: htmlspecialchars() expects parameter 1 to be string, object given in Drupal\Component\Utility\Html::escape() (line 424 of /var/www/html/web/core/lib/Drupal/Component/Utility/Html.php)
#0 /var/www/html/web/core/includes/bootstrap.inc(600): _drupal_error_handler_real(2, 'htmlspecialchar...', '/var/www/html/w...', 424, Array)
#1 [internal function]: _drupal_error_handler(2, 'htmlspecialchar...', '/var/www/html/w...', 424, Array)
#2 /var/www/html/web/core/lib/Drupal/Component/Utility/Html.php(424): htmlspecialchars(Object(Drupal\Core\Url), 11, 'UTF-8')
#3 /var/www/html/web/core/lib/Drupal/Component/Render/FormattableMarkup.php(221): Drupal\Component\Utility\Html::escape(Object(Drupal\Core\Url))
#4 /var/www/html/web/core/lib/Drupal/Core/StringTranslation/TranslatableMarkup.php(195): Drupal\Component\Render\FormattableMarkup::placeholderFormat('@author \xE2\x80\x93 <a ...', Array)
#5 /var/www/html/web/core/lib/Drupal/Component/Utility/ToStringTrait.php(15): Drupal\Core\StringTranslation\TranslatableMarkup->render()
#6 /var/www/html/web/sites/default/files/php/twig/5ea882e7be937_comment.html.twig_5YGT0bAF_4T1MIEmNtgM1ZX7W/HCL1g3xbzqQ2qIAb-_hHUUdDJjVVpim7tYB-qi-j4h8.php(80): Drupal\Core\StringTranslation\TranslatableMarkup->__toString()
#7 /var/www/html/vendor/twig/twig/src/Template.php(455): __TwigTemplate_64abb5c464dda24161914a28f6a08ce58d0b342f5347d0c55c689eb8323d5acc->doDisplay(Array, Array)
#8 /var/www/html/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /var/www/html/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array)
#10 /var/www/html/web/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array)
#11 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('themes/jeffgeer...', Array)
#12 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\Core\Theme\ThemeManager->render('comment', Array)
#13 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(444): Drupal\Core\Render\Renderer->doRender(Array)
#14 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender(Array, false)
#15 /var/www/html/web/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\Core\Render\Renderer->render(Array)
#16 /var/www/html/web/sites/default/files/php/twig/5ea882e7be937_field--comment.html.twig_D1VBgT12HIypygtkerrgvZlUU/QGle11mOh6SyBYSTM8DSIj5u16z_CFOXY3sXEhMlgy4.php(89): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#17 /var/www/html/vendor/twig/twig/src/Template.php(455): __TwigTemplate_b93024b24b018a6bc0e5f3cd6487b188671f4b5d0d9fd1b7e7e64dbabf16a9f6->doDisplay(Array, Array)
#18 /var/www/html/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /var/www/html/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array)
#20 /var/www/html/web/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array)
#21 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('core/themes/cla...', Array)
#22 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\Core\Theme\ThemeManager->render('field', Array)
#23 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(444): Drupal\Core\Render\Renderer->doRender(Array)
#24 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender(Array, false)
#25 /var/www/html/web/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\Core\Render\Renderer->render(Array)
#26 /var/www/html/web/sites/default/files/php/twig/5ea882e7be937_node.html.twig_Q_r-oj8RBX8urhYfoi6O1Oug1/71k0mtTWxtuHd3uEAHv0y2jWov8Wh67J02rholIC6pM.php(129): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#27 /var/www/html/vendor/twig/twig/src/Template.php(455): __TwigTemplate_877dbf8a58c10b74d1cd7df929c8e8709709393ac254d58f85b24aed610dd9ea->doDisplay(Array, Array)
#28 /var/www/html/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /var/www/html/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array)
#30 /var/www/html/web/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array)
#31 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('themes/jeffgeer...', Array)
#32 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\Core\Theme\ThemeManager->render('node', Array)
#33 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender(Array, false)
#34 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(226): Drupal\Core\Render\Renderer->render(Array, false)
#35 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#36 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(227): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#37 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(117): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#38 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#39 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#40 /var/www/html/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#41 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(156): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent))
#42 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#43 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#44 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#45 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#46 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#47 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#48 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#49 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#50 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(694): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#51 /var/www/html/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#52 {main}
```

**Comment by geerlingguy** [comment]
Hmm... even if I comment out all my `hook_preprocess_comment()` code the content of the comment doesn't display, and there are no other errors :/

I thought it was a problem in here:

```php
  // Build the 'submitted by' text.
  $variables['submitted'] = t('@author – <a href=":permalink">@time ago</a>', [
    '@author' => $variables['author'],
    ':permalink' => $uri,
    '@time' => $variables['created'],
  ]);
```

But that seems not to be the case.

**Comment by geerlingguy** [comment]
Hmm... even if I comment out all my `hook_preprocess_comment()` code the content of the comment doesn't display, and there are no other errors :/

I thought it was a problem in here:

```php
  // Build the 'submitted by' text.
  $variables['submitted'] = t('@author – <a href=":permalink">@time ago</a>', [
    '@author' => $variables['author'],
    ':permalink' => $uri,
    '@time' => $variables['created'],
  ]);
```

But that seems not to be the case.

**Comment by geerlingguy** [comment]
Fix for the notices is:

```php
  // Build the 'submitted by' text.
  $variables['submitted'] = t('@author – <a href=":permalink">@time ago</a>', [
    '@author' => $variables['author'],
    ':permalink' => $uri->toString(),
    '@time' => $variables['created'],
  ]);
```

(Note the `->toString()`).

Still digging on why the comment body is not displaying. I can see the `comment_body_value` in the database :/

**Comment by geerlingguy** [comment]
Interesting. It seems like many older comments had no `langcode` value in `comment_field_data`, and had `langcode` set to `en` in `comment__comment_body`.

If I manually set _both_ of those values to `und`, then cleared all caches, the comment body field appears.

**Comment by geerlingguy** [comment]
Illustrations to the point above:

<img width="1257" alt="comment-1-works" src="https://user-images.githubusercontent.com/481677/80535919-2abeb700-8967-11ea-9f58-33d48ec80306.png">

<img width="1257" alt="comment-1-works-2" src="https://user-images.githubusercontent.com/481677/80535924-2e523e00-8967-11ea-8801-55451120a59b.png">

And on the site, after clearing caches:

<img width="982" alt="Screen Shot 2020-04-28 at 3 45 21 PM" src="https://user-images.githubusercontent.com/481677/80535985-4a55df80-8967-11ea-9c4f-1c68800c230c.png">

**Comment by geerlingguy** [comment]
Related issue on Drupal.org: [Migrating content with missing language is problematic](https://www.drupal.org/project/drupal/issues/2859359).

**Comment by geerlingguy** [comment]
I originally tried setting a default of `und` in the `upgrade_d7_comment` migration:

```yaml
  langcode:
    -
      plugin: default_value
      source: language
      default_value: und
```

But that still resulted in rows with no defined langcode. So I went nuclear, and just forced it in each row in my custom module like so:

```php
/**
 * Implements hook_migrate_prepare_row().
 */
function custom_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $migration_id = $migration->id();

  // Force 'und' language for comments.
  if ($migration_id == 'upgrade_d7_comment') {
    $row->setSourceProperty('language', 'und');
  }
}
```
